name: Commit comments
on:
  push:
    branches:
      - main

jobs:
  comments:
    name: Commit comments
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install dependencies
        run: npm install @actions/core @actions/github fs

      - name: Comment on commit
        run: node comments.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
