name: Commit comments
on:
  push:
    branches:
      - master

jobs:
  comments:
    name: Commit comments
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install @actions/core @actions/github

      - name: Run comment.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node comment.js

      - name: Comment on commit
        uses: Discord-Datamining/comments-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
