name: Commit comments
on:
  push:
    branches:
      - main

jobs:
  comments:
    permissions:
      contents: write
      packages: write
      pull-requests: write
      issues: write
      statuses: write
      deployments: write
    name: Commit comments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install dependencies
        run: npm install @actions/core @actions/github fs

      - name: Comment on commit
        run: node ./.github/workflows/comments.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
